### PR TITLE
Update the routes in Branding-the-NuGet-Gallery.md

### PR DESCRIPTION
**Pull request by scottbommarito**
We are updating the routes of the form "packages/<action>" to "packages/manage/<action>". This file made a couple references to the old routes.

@harikmenon @maartenba @xavierdecoster

### CODE REVIEW

**Comment by harikmenon** [comment]
:shipit:

**Comment by maartenba** [comment]
LGTM, don't merge until gallery changes are live though :-)

**Comment by karann-msft** [comment]
@maartenba @harikmenon @scottbommarito  are the gallery changes live? this is to ask if we are good to merge this PR?

**Comment by karann-msft** [comment]
Closing the PR as this doc has moved here https://github.com/NuGet/NuGetGallery/wiki/Branding-the-NuGet-Gallery

@scottbommarito please make the relevant changes to the wiki. Thanks.

**Pull request closed without merging**
