### PR TITLE
Adding versions to -configfile docs to clarify behavior

### PR DESCRIPTION
**Pull request by mishra14**
Adding versions to the -configfile switch docs to have better clarity about the behavior for different versions of nuget.exe

Addresses- https://github.com/NuGet/Home/issues/3208 https://github.com/NuGet/Home/issues/3221

cc : @harikmenon  @karann-msft

### CODE REVIEW

**Comment by mishra14** [comment]
@karann-msft : ping!

**Comment by karann-msft** [comment]
@mishra14 please resolve the conflicts.
cc: @harikmenon

**Comment by mishra14** [comment]
@karann-msft : Done. Please take a look.

**Comment by karann-msft** [comment]
Awesome! Thanks! LGTM. Merging now.

**Pull request merged**
