### PR TITLE
Added Locals command

### PR DESCRIPTION
**Pull request by csharpfritz**

### CODE REVIEW

**Comment by yishaigalatzer** [comment]
@csharpfritz i'm not sure about the interactive and config file flags in this command @xavierdecoster might be able to provide more input

**Comment by csharpfritz** [comment]
np... I see them in the command-line help docs.  I'll clean up if need be in this branch prior to rebase and merge at deployment time

**Comment by xavierdecoster** [comment]
Those flags (interactive, config) are available on all nuget.exe commands as they are in the base class. This command does not use them though.

**Comment by yishaigalatzer** [comment]
Yup - That was my point. So we should remove them or say they are not applicable

**Comment by csharpfritz** [comment]
Removed



Jeff

**Pull request merged**
