### PR TITLE
Mention the new -DirectDownload switch for nuget.exe install and update

### PR DESCRIPTION
**Pull request by joelverhagen**
/cc @harikmenon @karann-msft

### CODE REVIEW

**Comment by karann-msft** [comment]
@joelverhagen is the going to be part of 3.5 or 3.6?

**Comment by joelverhagen** [comment]
nuget.exe, 3.6

**Comment by karann-msft** [comment]
then you should be attempting to merge into the 3.6 branch and not master.

**Comment by joelverhagen** [comment]
Rebased. Good to go @karann-msft?

**Comment by karann-msft** [comment]
LGTM. Merging.

**Pull request merged**
