### PR TITLE
Updated minimal requirements for NuGet development.

### PR DESCRIPTION
**Pull request by alpaix**
Updated getting started page with VS2015.1 and ASP.NET 5 requirements.

https://github.com/NuGet/Home/issues/1790.

### CODE REVIEW

**Comment by alpaix** [comment]
@csharpfritz could you please review this change?

**Comment by csharpfritz** [comment]
Sure.. I'll dig into it

**Comment by csharpfritz** [comment]
Can you update the commands that need to be keyed in at the command-line to use the back-tick code markup?  Like `this`

**Comment by alpaix** [comment]
Back ticks give different effect on docs site. I formatted command-line statements the same way as others on that page.

image

**Comment by csharpfritz** [comment]
Looks good!

**Pull request merged**
