### PR TITLE
Rewrite settings doc page

### PR DESCRIPTION
**Pull request by tbolon**
Replace the table layout with heading and paragraphs
Clarify sections and keys
Convert html to markdown syntax

I am planning to remove the [NuGet Configuration Settings](http://docs.nuget.org/consume/nuget-config-file#nuget-configuration-settings) in [http://docs.nuget.org/consume/nuget-config-file]() as it seems to be a duplicate of this page.

We could also remove this page and enhance the nuget-config-file instead, but for compatibility reasons I think removing the page is too dangerous.

### CODE REVIEW

**Comment by tbolon** [comment]
Hi, any news ? I have rebased my change to include the recent [commit](https://github.com/NuGet/NuGetDocs/commit/47f4a904858d1408c1228c74d5b551c0320113c7)

**Comment by yishaigalatzer** [comment]
@tbolon thanks for your contribution.

@csharpfritz would you mind reviewing this change?

**Comment by csharpfritz** [comment]
Reviewing today...  there is a merge conflict and I need to verify no
content was dropped in the reformatting



Jeff

**Comment by csharpfritz** [comment]
This looks like a good cleanup of a page format that we are no longer using.  Please fix the angle-brackets in the second repository path sample, they're currently formatted as HTML encoded characters.

We can then accept this PR

**Comment by tbolon** [comment]
I have resolved all conflicts and fix the comments above:

* the second repository path sample has been fixed
* the note has been removed by merging ab4e25a

Please note that when doing this, I have seen that now the page [NuGet Config File](http://docs.nuget.org/Consume/NuGet-Config-File#nuget-configuration-settings) has a section "NuGet Configuration Settings" which duplicates most of the entries.

Perhaps this part should be simply replaced by a link to this page instead ?

**Comment by yishaigalatzer** [comment]
@csharpfritz can you take another look at this?

**Comment by csharpfritz** [comment]
Merging and deploying after conflict resolution

**Pull request closed without merging**
