### PR TITLE
Added Known issue for authentication on VSTS Feeds

### PR DESCRIPTION
**Pull request by harikm86**

### CODE REVIEW

**Comment by harikm86** [comment]
@rrelyea @alpaix : Can you guys do a tech review. I understood the double encryption problem but not sure how the single statement solves this. Is it because we are using the update command?

**Comment by alpaix** [comment]
Playing with add/update commands can be tricky. The real 100% sure workaround would be storing passwords in clear text whenever it's possible. This can be achieved with extra switch `-StorePasswordInClearText`. Does it make sense?

**Comment by harikm86** [comment]
Okay. Let me make that change.

**Comment by harikm86** [comment]
#https://github.com/NuGet/NuGetGallery/issues/3008 - added fix for the broken link issue

**Pull request merged**
