### PR TITLE
Adding a help doc for locals command used by VS Package Manager Settings

### PR DESCRIPTION
**Pull request by mishra14**
Adding a help doc for locals command used by VS Package Manager Settings.

Based on offline discussions with @harikmenon  and @rrelyea .

The corresponding UI change - https://github.com/NuGet/Home/issues/3289

//cc: @karann-msft @harikmenon

### CODE REVIEW

**Comment by harikmenon** [comment]
@karann-msft to review,

**Comment by mishra14** [comment]
@karann-msft : Moved the doc into the right folder. Please feel free to review.

**Comment by karann-msft** [comment]
LGTM :shipit:

**Comment by mishra14** [comment]
Merged: https://github.com/NuGet/NuGetDocs/commit/d497124e3666cebe9bf8df9147f34e2f498801cd

**Pull request closed without merging**
